apiVersion: v1
kind: Template
metadata:
  name: nginx
  annotations:
    description: "NGINX is a free, open-source, high-performance HTTP server." 
    tags: "webserver,nginx" 
labels:      
  template: nginx
  group: nginx
  version: 1.0.0
objects:   
- kind: Service
  apiVersion: v1
  metadata:
    name: nginx-front
  spec:
    selector:
      name: nginx-front
    ports:
    - name: nginx
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 0
    portalIP: ''
    type: ClusterIP
- kind: ImageStream
  apiVersion: v1
  metadata:
    name: nginx
  spec:
    dockerImageRepository: koscicz/nginx
    tags:
    - name: latest
- kind: Route
  apiVersion: v1
  metadata:
    name: nginx-front-route
  spec:
    host: ''
    to:
      kind: Service
      name: nginx-front
- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: nginx
  spec:
    selector:
      name: nginx-front
    strategy:
      type: Rolling
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - nginx
        from:
          kind: ImageStreamTag
          name: nginx:latest
    replicas: 1
    template:
      metadata:
        name: nginx-dummy
        labels:
          name: nginx-front
      spec:
        containers:
        - name: nginx
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - name: data
            mountPath: "/usr/share/nginx/html"
        volumes:
        - name: data
          emptyDir:
            medium: ''
