.TH "NGINX " "1" " Container Image Pages" "Jan Koscielniak" "June 19, 2017"  ""


.SH NAME
.PP
nginx \- HTTP and reverse proxy server, mail proxy server


.SH DESCRIPTION
.PP
This image is meant to provide a nginx web server. Image is based on Fedora 26 Boltron and nginx module.

.PP
This repository contains file nginx.conf in files folder, where you can configure all the settings you need for nginx to suit your needs. However, please don't change the following lines, as they are needed for proper functionality in a container.

.PP
.RS

.nf
error\_log stderr;
daemon off;

.fi
.RE

.PP
These lines will redirect error log to stderr and prevent nginx from demonizing itself, which if enabled, would result in docker stopping the container right after starting it, because the root process would exit right after spawning worker processes.


.SH USAGE
.PP
You can run this image in docker like this:

.PP
.RS

.nf
# docker run \-p 8080:80 \-v $DIR:/var/www/html/

.fi
.RE

.PP
$DIR in this context is the root of your web application.

.PP
Image can also be run in Openshift. You can obtain the template in the repository of this image \- 
\[la]https://github.com/container-images/nginx\[ra]. You also need to have SCC RunAsUser set to RunAsAny. Then run:

.PP
.RS

.nf
# oc create \-f openshift\-template.yml

.fi
.RE


.SH ENVIRONMENT VARIABLES
.PP
There are no environment variables to be set.


.SH SECURITY IMPLICATIONS
.PP
\-p 8080:80
    Exposes port 80 on the container and forwards it to port 8080 on the host.

.PP
This container runs as root user.


.SH HISTORY
.PP
Similar to a Changelog of sorts which can be as detailed as the maintainer wishes.


.SH SEE ALSO
.PP
Github page for this container with detailed description: 
\[la]https://github.com/container-images/nginx\[ra]
